package cn.com.bettle.net.servlet;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.PropertyConfigurator;

public class Log4jInit extends HttpServlet {
	
	 private final String WEB_APP_ROOT_DEFAULT = "webapp.root";
	 public void init() throws ServletException {
	  String prefix = getServletContext().getRealPath("/");
	  String webAppRootKey = getServletConfig().getInitParameter("webAppRootKey");
	  if(webAppRootKey == null || webAppRootKey.length() < 1){
		  webAppRootKey = WEB_APP_ROOT_DEFAULT;
	  }
	  System.setProperty(webAppRootKey, prefix);
	  
	  String propfile = getServletConfig().getInitParameter("log4j-config-file");
	  if (propfile != null) {
		   PropertyConfigurator.configure(prefix + propfile);
	  }
	 }
	 
	 protected void doGet(HttpServletRequest request,HttpServletResponse response) throws ServletException, IOException {
	  // TODO Method stub generated by Lomboz
	 }
	 protected void doPost(HttpServletRequest request,HttpServletResponse response) throws ServletException, IOException {
	  // TODO Method stub generated by Lomboz
	 }
}
