DROP TABLE IF EXISTS `t_e911`;

CREATE TABLE `t_e911` (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  `PHONENUM` VARCHAR(14) DEFAULT NULL,
  `DATES` VARCHAR(5) DEFAULT NULL,
  `TIMES` VARCHAR(5) DEFAULT NULL,
  `ESN` VARCHAR(5) DEFAULT NULL,
  `ADDRH` VARCHAR(8) DEFAULT NULL,
  `ADDRHS` VARCHAR(4) DEFAULT NULL,
  `ADDRPRE` VARCHAR(2) DEFAULT NULL,
  `ADDRST` VARCHAR(48) DEFAULT NULL,
  `ADDRSFIX` VARCHAR(4) DEFAULT NULL,
  `ADDRPST` VARCHAR(2) DEFAULT NULL,
  `CITY` VARCHAR(18) DEFAULT NULL,
  `CUSTNAME` VARCHAR(32) DEFAULT NULL,
  `ADDINFO` VARCHAR(20) DEFAULT NULL,
  `WIRELESSX` VARCHAR(11) DEFAULT NULL,
  `WIRELESSY` VARCHAR(10) DEFAULT NULL,
  `STATION` VARCHAR(3) DEFAULT NULL,
  `SERVT` VARCHAR(4) DEFAULT NULL,
  `ADDRESS` VARCHAR(60) DEFAULT NULL,
  `DATETIMES` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `t_e911_current`;

CREATE TABLE `t_e911_current` (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  `PHONENUM` VARCHAR(14) DEFAULT NULL,
  `DATES` VARCHAR(5) DEFAULT NULL,
  `TIMES` VARCHAR(5) DEFAULT NULL,
  `ESN` VARCHAR(5) DEFAULT NULL,
  `ADDRH` VARCHAR(8) DEFAULT NULL,
  `ADDRHS` VARCHAR(4) DEFAULT NULL,
  `ADDRPRE` VARCHAR(2) DEFAULT NULL,
  `ADDRST` VARCHAR(48) DEFAULT NULL,
  `ADDRSFIX` VARCHAR(4) DEFAULT NULL,
  `ADDRPST` VARCHAR(2) DEFAULT NULL,
  `CITY` VARCHAR(18) DEFAULT NULL,
  `CUSTNAME` VARCHAR(32) DEFAULT NULL,
  `ADDINFO` VARCHAR(20) DEFAULT NULL,
  `WIRELESSX` VARCHAR(11) DEFAULT NULL,
  `WIRELESSY` VARCHAR(10) DEFAULT NULL,
  `STATION` VARCHAR(3) DEFAULT NULL,
  `SERVT` VARCHAR(4) DEFAULT NULL,
  `ADDRESS` VARCHAR(60) DEFAULT NULL,
  `DATETIMES` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DELETE FROM t_e911_current WHERE 1 ORDER BY ID LIMIT 1;

SELECT * FROM t_e911_current